version: '3.8'

services:
  movie-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 14
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll=2000"]
